# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  #prepared vm with open-jdk7 and TC7
  config.vm.box = "prcs32-jdk7-tc7"
  config.vm.network :private_network, ip: '192.168.56.15'
  config.vm.network :forwarded_port, guest: 8844, host: 8844
  config.vm.hostname = "example-1"

  config.vm.synced_folder "./target", "/tmp/target/"

  config.vm.provider :virtualbox do |vb|
   # Don't boot with gui
   vb.gui = false
   vb.name = "example-1"
   vb.customize ["modifyvm", :id, "--memory", "1024"]
   vb.customize ["modifyvm", :id, "--cpus", 2]
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.module_path = "modules"
    puppet.manifest_file  = "example-1.pp"
    puppet.options = "--verbose"
  end #puppet 

end